export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
HIST_STAMPS="dd/mm/yyyy"
plugins=(git)

source $ZSH/oh-my-zsh.sh

MANPATH="/usr/local/man:$MANPATH"
PATH="$HOME/.cargo/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"

mkdir -p "$(xdg-user-dir PICTURES)/Screenshots"

eval "$(starship init zsh)"

alias_comands()
{
    if which $2 > /dev/null 2>&1; then
        alias $1=$2
    fi
}

if which wf-recorder > /dev/null 2>&1; then
    alias rc='wf-recorder --audio -g --force-yuv "$(slurp)"'
fi

if which sk > /dev/null 2>&1; then
    alias sk="sk --ansi -i -c 'rg --color=always --line-number "{}"' --preview '$HOME/.main/scrips/preview.sh {}'"
fi

alias_comands ls exa
alias_comands cat bat
alias_comands time hyperfine
alias_comands htop btm
alias_comands find fd
alias_comands du dust

# tab multiplexer configuration: https://github.com/austinjones/tab-rs/
source "/home/burato/.local/share/tab/completion/zsh-history.zsh"
# end tab configuration

